### ISSUE TITLE
invalid byte sequence in US-ASCII

### ISSUE THREAD

**Issue by zenminimalist** [rccavalcanti/fyodor#6]
`Using config at /Users/MY_USER/.config/fyodor/fyodor.toml.
Using custom template at /Users/MY_USER/.config/fyodor/template.erb.

invalid byte sequence in US-ASCII` 

I'm getting this error without any file output. Am I missing something?

**Comment by rc2dev** [comment]
Hi,

What command are you running? Can you run it again with the `-t`flag and post the output here?

Thanks!

**Comment by zenminimalist** [comment]
I just used the following command:  **fyodor -t /Users/David/Downloads/My\ Clippings.txt** and get the following response:

`Using config at /Users/David/.config/fyodor/fyodor.toml.
Using custom template at /Users/David/.config/fyodor/template.erb.

/opt/homebrew/Cellar/gem-fyodor/0.3.3/gems/fyodor-0.3.3/lib/fyodor/clippings_parser.rb:27:in `end_entry?': invalid byte sequence in US-ASCII (ArgumentError)
	from /opt/homebrew/Cellar/gem-fyodor/0.3.3/gems/fyodor-0.3.3/lib/fyodor/clippings_parser.rb:16:in `block in parse'
	from /opt/homebrew/Cellar/gem-fyodor/0.3.3/gems/fyodor-0.3.3/lib/fyodor/clippings_parser.rb:14:in `each'
	from /opt/homebrew/Cellar/gem-fyodor/0.3.3/gems/fyodor-0.3.3/lib/fyodor/clippings_parser.rb:14:in `parse'
	from /opt/homebrew/Cellar/gem-fyodor/0.3.3/gems/fyodor-0.3.3/bin/fyodor:39:in `run'
	from /opt/homebrew/Cellar/gem-fyodor/0.3.3/gems/fyodor-0.3.3/bin/fyodor:17:in `main'
	from /opt/homebrew/Cellar/gem-fyodor/0.3.3/gems/fyodor-0.3.3/bin/fyodor:59:in `<top (required)>'
	from /opt/homebrew/bin/fyodor:6:in `load'
	from /opt/homebrew/bin/fyodor:6:in `<main>'`

**Comment by rc2dev** [comment]
Thanks for the answer!

It looks like an encoding issue. Can you enter the following lines and then, in the same terminal, try to run fyodor again?

```sh
export LANG=en_US.UTF-8
export LANGUAGE=en_US.UTF-8
export LC_ALL=en_US.UTF-8
```

**Comment by zenminimalist** [comment]
Ok, now it worked. 

I got the following: 

`=> 3 books found
=> Ignored 1 empty and 7 duplicated entries.
  Highlights: 589
       Notes: 0
   Bookmarks: 0
       Clips: 0
Unrecognized: 0
-------------------
       TOTAL: 589

ALL entries were correctly parsed.

Writing to /Users/David/fyodor_output...
/opt/homebrew/Cellar/gem-fyodor/0.3.3/gems/fyodor-0.3.3/lib/fyodor/output_generator.rb:14: warning: Passing safe_level with the 2nd argument of ERB.new is deprecated. Do not use it, and specify other arguments as keyword arguments.
/opt/homebrew/Cellar/gem-fyodor/0.3.3/gems/fyodor-0.3.3/lib/fyodor/output_generator.rb:14: warning: Passing trim_mode with the 3rd argument of ERB.new is deprecated. Use keyword argument like ERB.new(str, trim_mode: ...) instead.
/opt/homebrew/Cellar/gem-fyodor/0.3.3/gems/fyodor-0.3.3/lib/fyodor/output_generator.rb:14: warning: Passing safe_level with the 2nd argument of ERB.new is deprecated. Do not use it, and specify other arguments as keyword arguments.
/opt/homebrew/Cellar/gem-fyodor/0.3.3/gems/fyodor-0.3.3/lib/fyodor/output_generator.rb:14: warning: Passing trim_mode with the 3rd argument of ERB.new is deprecated. Use keyword argument like ERB.new(str, trim_mode: ...) instead.
/opt/homebrew/Cellar/gem-fyodor/0.3.3/gems/fyodor-0.3.3/lib/fyodor/output_generator.rb:14: warning: Passing safe_level with the 2nd argument of ERB.new is deprecated. Do not use it, and specify other arguments as keyword arguments.
/opt/homebrew/Cellar/gem-fyodor/0.3.3/gems/fyodor-0.3.3/lib/fyodor/output_generator.rb:14: warning: Passing trim_mode with the 3rd argument of ERB.new is deprecated. Use keyword argument like ERB.new(str, trim_mode: ...) instead.`

Is there any way to have the md output file _without_ bullet points and without the "highlight @ page 14, loc. 294-299" and just a new line after each highlight? Basically, just like so:

Hightight 1 blabalbalbala Hightight 1 blabalbalbalaHightight 1 blabalbalbalaHightight 1 blabalbalbala

Hightight 2 blabalbalbala Hightight 2 blabalbalbala Hightight 2 blabalbalbala Hightight 2 blabalbalbala 

If so, what would I have to change/delete in the code (not a programmer, but can follow directions 🙂)

Additionally:
- Is there a way to have as the first two lines of each output file?

Book: Thinking, Fast and Slow  
Author: Daniel Kahneman

- Is there a way to change the format of the output filename like so: 
Book Highlights - Author Lastname, Firstname - Book Title
Example: **Book Highlights - Kahneman, Daniel - Thinking, Fast and Slow Author**




Book: Thinking, Fast and Slow  
Author: Daniel Kahneman

**Comment by rc2dev** [comment]
> Ok, now it worked.

**Comment by rc2dev** [comment]
> Ok, now it worked.

Great!

> Is there any way to have the md output file without bullet points ...

Sure, just replace `render_entries` for whatever you'd like. For example, to output this:

```
Highlight 1

Highlight 2

Note 1

Highlight 3
...
```

You could write something like this:

```erb
<% for entry in regular_entries %>
  <%= entry.text.strip %>
<% end %>
```

> Is there a way to have as the first two lines of each output file?

Sure, with something like this:

```erb
Book: <%= @book.title %>
Author: <%= @book.author %>
```

On the README, there is a link to a file with the variables you can try to use in your template. Also, check the ERB documentation if you need to know how the templating engine works.

> Is there a way to change the format of the output filename...

Not at this time. For now, only the file extension is customizable.


Those questions were already out-of-topic, so if you have follow-up questions, I ask you to open a new separate issue. :-) Thanks!
