### ISSUE TITLE
Small change to Fyodor's default template possible? (Shift return)

### ISSUE THREAD

**Issue by zenminimalist** [rccavalcanti/fyodor#7]
Thanks for the fantastic help with the templating and other issues! By the way, I find your app much better than the paid clipping.io that doesn't even recognize duplicates, and I have to do each file manually 🤷🏼‍♂️

I have the following template, which is almost perfect for what I want. 

`<%# Fyodor's default template. -%>
#<%=@book.title %>

**Book:** <%= @book.title %>
**Author:** <%= @book.author %>
<% for entry in regular_entries %>
<%= entry.text.strip %>
<% end %>`

**One small change I want to make is:**
Each highlight should be on a separate line (which is currently the case 👍🏼). However, I would like to have the book and author only have a "Shift return", as this does NOT return a new line between **Book** and **Author** when converting it to Word, PDF etc. 

So instead of it displaying the following (after converting to whatever output format my markdown has)

**Book:** The Intelligent Investor, Rev. Ed

**Author:** Benjamin Graham

it does this: 

**Book:** The Intelligent Investor, Rev. Ed
**Author:** Benjamin Graham

[**Here's**](https://imgur.com/a/0VX0cEM) a gif of what I mean, in case I didn't explain it well enough. 

I'm not sure this is even possible, but my Markdown editor does remove the new line after **Book** if I "Shift-Enter".

**Comment by rc2dev** [comment]
Thanks for the compliments!

So what I understand is that when you convert your markdown to PDF, HTML, etc, you want it to display this:

```
Book: Book title
Author: Author name
```

And not

```
Book: Book title
...<some space>...
Author: Author name
```

Have you tried adding a backslash to the book line? Like this:

```erb
Book: <%= @book.title %>\
Author: <%= @book.author %>
```

This works for me.

**Comment by zenminimalist** [comment]
Thanks. It doesn't work for me. But even _without_ the \ it works with Typora, Obsidian...just fine without a space in between.

However, I narrowed it down to the app I'm using "Ulysses". It must be doing something "special" and not respecting the formating (with or without /), as it **DOES** work with Typora, Obsidian without a /...

So, in case somebody is using the Ulysses and wants the same formating it currently isn't working. I'll hit up the Ulysses support and hopefully, they'll fix it *just for me* 😇 (doubt it).

Thanks for all the help!

**Comment by rc2dev** [comment]
I'm not familiar with Ulysses, but it might have a way to display the markdown code without the rendering. For example in Typora you can go to `View -> Source code mode`, or click the `</>` icon on the left bottom.

I'd suggest you to look for such a option, so you can see what it is doing behind the scenes when you do a `Shift+Return`. :)
