### ISSUE TITLE
Idea/Feature Improvement: Output multiple doc formats with one command

### ISSUE THREAD

**Issue by zenminimalist** [rccavalcanti/fyodor#9]
For me your tool is perfect. I normally convert my highlights in multiple formats (md, docx and pdf). So I thought about a feature that could improve the output workflow by adding another attribute in the toml file, which would be "formats".

```
filename = "Highlights - %{title} - %{author_fill}.md"
formats = md, pdf, docx
```

This would then give you the following 3 output files with **one** command:

Highlights - Random Book - Awesome Author.md
Highlights - Random Book - Awesome Author.pdf
Highlights - Random Book - Awesome Author.docx

I'm sure there are free open source pdf and docx conversion libraries out there that one could utilize without having to reinvent the wheel. 

Possible caveat:
The only thing that could add complexity is the formatting of pdf and docx files (how the file would be formated e.g. A4, US, etc, margins, heading, font, font size,...). Although one could add a default template and have the users edit it themselves if they want. 

What are your thoughts?

**Comment by rc2dev** [comment]
Thanks for the suggestion!

I'm not a fan of making Fyodor aware of any output format. I'd much prefer to stick to the unix philosophy and try to just do one thing well, which in this case is parsing MyClippings.

For the output, we provide a sane default, and the user is invited to change it to whatever it finds appropriate (via custom templates and filenames) and even parse it again to another format with another tool (the unix way).

Some examples:

- The user wants HTML output. He just provides a simple `tempĺate.erb` with the HTML structure and change the filename to `whatever.html`. Done. Alternatively, he keeps the default output and pipes the markdown into an application to convert to HTML.

- He needs a PDF file. He can keep the default markdown output and easily pipe it into pandoc, getting the PDF in seconds. Etc, etc.

Depending on external libraries isn't so straightforward. We'd have more bugs, more maintenance, and users would still be limited to whatever formats I pick. I'd rather focus on parsing and giving the user control via a customizable plain text output.

Best regards!
